package com.pict.Timetable;

import java.util.HashMap;

public class SE4 extends SE {

	public void addLecturesTimings() {
		LECTURE_TIMINGS[0] = "10:00-11:00";
		LECTURE_TIMINGS[1] = "11:00-12:00";
		LECTURE_TIMINGS[2] = "12:00-13:00";
		LECTURE_TIMINGS[3] = "13:00-13:45";
		LECTURE_TIMINGS[4] = "13:45-14:45";
		LECTURE_TIMINGS[5] = "14:45-15:45";
		LECTURE_TIMINGS[6] = "15:45-16:00";
		LECTURE_TIMINGS[7] = "16:00-17:00";
		LECTURE_TIMINGS[8] = "17:00-18:00";
	}

	public void initialise() {
		TIME_TABLE = new HashMap<String, String>();
		TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[0], "DS(E1)\nDS(E2)\nDS(E3)\nDS(E4)");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[0] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");

        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[0], "DS");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[1] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");

        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[0], "DS");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[2] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");

        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[0], "DS");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[3] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");

        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[0], "DS");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[4] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");

        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[0], "DS");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[1], "DS1");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[2], "Short Break");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[3], "DS3");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[4], "DS4");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[5], "Lunch Break");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[6], "DS6");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[7], "DS7");
        TIME_TABLE.put(DAYS[5] + SEMI_COLON + LECTURE_TIMINGS[8], "DS8");
	}

}
